FROM node:14.9.0-alpine as build
ARG meili_host
ARG meili_public_key
ENV REACT_APP_MEILI_HOST=$meili_host
ENV REACT_APP_MEILI_PUBLIC_KEY=$meili_public_key

WORKDIR /edd
COPY package*.json ./
RUN npm install
COPY . ./
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /edd/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]